name: "protonmail-bridge"

services:

####################
# Proton Mail Bridge
# Using shenxn/protonmail-bridge-docker
# https://github.com/shenxn/protonmail-bridge-docker
####################

  protonmail-bridge:
    container_name: protonmail-bridge
    image: shenxn/protonmail-bridge:latest
    
    networks:
      - proton-bridge-net
    
    ports:
      - 1025:25/tcp
    
    # Expose actual bridge ports for Docker network access
    # (shenxn image socat forwards to wrong ports for v3)
    expose:
      - "1026"   # SMTP direct (Proton Bridge v3)
      - "1144"   # IMAP direct (Proton Bridge v3)

    environment:
      TZ: ${TZ}
    
    volumes:
      - ${CONFIGDIR}/protonmail-bridge:/root
    
    labels:
      - diun.enable=true
      - homepage.group=Back End
      - homepage.name=Proton Mail Bridge
      - homepage.icon=protonmail
      - homepage.description=Email bridge for SMTP/IMAP
      - homepage.weight=852
    
    restart: unless-stopped

networks:
  proton-bridge-net:
    name: proton-bridge-net
    external: true